package helper

import (
	"fmt"
	"testing"

	corev1 "k8s.io/api/core/v1"

	devboxv1alpha2 "github.com/labring/sealos/controllers/devbox/api/v1alpha2"
)

func TestGenerateEnvProfile(t *testing.T) {
	tests := []struct {
		name string
		envs []corev1.EnvVar
		want string
	}{
		{
			name: "no env variables",
			envs: nil,
			want: "# Generated by Sealos Devbox\n",
		},
		{
			name: "multiple env variables",
			envs: []corev1.EnvVar{
				{Name: "FOO", Value: "bar"},
				{Name: "HELLO", Value: "world"},
			},
			want: "# Generated by Sealos Devbox\n" +
				"export FOO=\"bar\"\n" +
				"export HELLO=\"world\"\n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			devbox := &devboxv1alpha2.Devbox{
				Spec: devboxv1alpha2.DevboxSpec{
					Config: devboxv1alpha2.Config{
						Env: tt.envs,
					},
				},
			}
			got := string(GenerateEnvProfile(devbox))
			fmt.Print(got)
			if got != tt.want {
				t.Fatalf("GenerateEnvProfile() = %q, want %q", got, tt.want)
			}
		})
	}
}
