apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dbprovider-frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dbprovider-frontend.labels" . | nindent 4 }}
data:
  .env: |-
    SEALOS_DOMAIN={{ .Values.dbproviderConfig.cloudDomain }}
    DESKTOP_DOMAIN={{ .Values.dbproviderConfig.cloudDomain }}
    SEALOS_PORT={{ include "dbprovider-frontend.portSuffix" . }}
    MONITOR_URL={{ .Values.dbproviderConfig.monitorUrl }}
    MINIO_URL={{ .Values.dbproviderConfig.minioUrl }}
    MINIO_ACCESS_KEY={{ .Values.dbproviderConfig.minioAccessKey }}
    MINIO_SECRET_KEY={{ .Values.dbproviderConfig.minioSecretKey }}
    MIGRATE_FILE_IMAGE={{ .Values.dbproviderConfig.migrateFileImage }}
    MINIO_PORT={{ .Values.dbproviderConfig.minioPort }}
    MINIO_BUCKET_NAME={{ .Values.dbproviderConfig.minioBucketName }}
    BACKUP_ENABLED={{ .Values.dbproviderConfig.backupEnabled }}
    SHOW_DOCUMENT={{ .Values.dbproviderConfig.showDocument }}
    GUIDE_ENABLED={{ .Values.dbproviderConfig.guideEnabled }}
    BILLING_URL={{ .Values.dbproviderConfig.billingUrl }}
    MANAGED_DB_ENABLED={{ .Values.dbproviderConfig.managedDbEnabled }}
    VLOGS_BASE_URL={{ .Values.dbproviderConfig.vlogsBaseUrl }}
  config.yaml: |-
    addr: :3000
