apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dbprovider-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "dbprovider-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "dbprovider-frontend.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        {{- include "dbprovider-frontend.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: cluster-version-reader
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: SEALOS_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: SEALOS_DOMAIN
            - name: DESKTOP_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: DESKTOP_DOMAIN
            - name: SEALOS_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: SEALOS_PORT
            - name: MONITOR_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: MONITOR_URL
            - name: MINIO_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: MINIO_URL
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: MINIO_SECRET_KEY
            - name: MIGRATE_FILE_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: MIGRATE_FILE_IMAGE
            - name: MINIO_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: MINIO_PORT
            - name: MINIO_BUCKET_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: MINIO_BUCKET_NAME
            - name: BACKUP_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: BACKUP_ENABLED
            - name: SHOW_DOCUMENT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: SHOW_DOCUMENT
            - name: GUIDE_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: GUIDE_ENABLED
            - name: BILLING_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: BILLING_URL
            - name: MANAGED_DB_ENABLED
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: MANAGED_DB_ENABLED
            - name: VLOGS_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "dbprovider-frontend.fullname" . }}-config
                  key: VLOGS_BASE_URL
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          image: {{ .Values.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          volumeMounts:
            - name: dbprovider-frontend-volume
              mountPath: /config.yaml
              subPath: config.yaml
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: dbprovider-frontend-volume
          configMap:
            name: {{ include "dbprovider-frontend.fullname" . }}-config
