apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloudserver-frontend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudserver-frontend.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret-app: {{ .Values.cloudserverConfig.jwtSecretApp | quote }}
