apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "cloudserver-frontend.labels" . | nindent 4 }}
  name: {{ include "cloudserver-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "cloudserver-frontend.selectorLabels" . | nindent 4 }}
