import type { NextPage } from 'next'
import Head from 'next/head'
import styles from './dashboard.module.css'
import { SearchOutlined } from '@ant-design/icons';
import { Tooltip, Button } from 'antd'

const Dashboard: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.menu}>header menu</div>

        <div className={styles.container}>
          <iframe className={styles.iframe} src="https://kubernetes-dashboard.cloud.sealos.io/" title="kubernetes-dashboard-cloud-sealos-io" />
        </div>

        <div className={styles.dock}>
          <Tooltip title="search">
            <Button type="primary" shape="circle" icon={<SearchOutlined />} />
          </Tooltip>
          <Tooltip title="search">
            <Button type="primary" shape="circle" icon={<SearchOutlined />} />
          </Tooltip>
        </div>
      </main>
    </div>
  )
}

export default Dashboard
