-- CreateEnum
CREATE TYPE "TagType" AS ENUM ('PROGRAMMING_LANGUAGE', 'USE_CASE', 'OFFICIAL_CONTENT');

-- AlterTable
ALTER TABLE "Tag" ADD COLUMN     "type" "TagType" NOT NULL DEFAULT 'OFFICIAL_CONTENT';
