FROM centos:7.4.1708
RUN yum install -y  wget && wget http://www.keepalived.org/software/keepalived-1.2.13.tar.gz && tar zxvf keepalived-1.2.13.tar.gz && yum install -y gcc-c++ openssl-devel openssl && \
    cd keepalived-1.2.13 && ./configure && make && make install && yum install -y net-tools
CMD keepalived -P -C -d -D -S 7 -f /etc/keepalived/keepalived.conf --dont-fork --log-console 
