FROM centos:7.4.1708
RUN yum install -y  wget  && yum install -y gcc-c++ openssl-devel openssl && yum install -y net-tools
RUN wget http://www.keepalived.org/software/keepalived-2.0.7.tar.gz && tar zxvf keepalived-2.0.7.tar.gz && cd keepalived-2.0.7 && ./configure && make && make install  
CMD keepalived -P -C -d -D -S 7 -f /etc/keepalived/keepalived.conf --dont-fork --log-console 
