apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "applaunchpad-frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "applaunchpad-frontend.labels" . | nindent 4 }}
data:
  .env: |-
    NODE_TLS_REJECT_UNAUTHORIZED={{ .Values.applaunchpadConfig.tlsRejectUnauthorized }}
  config.yaml: |-
    cloud:
      domain: {{ .Values.applaunchpadConfig.cloudDomain }}
      nodePortHost: {{ .Values.applaunchpadConfig.nodePortHost | quote }}
      port: {{ include "applaunchpad-frontend.releaseConfigPort" . | quote }}
      httpPort: {{ include "applaunchpad-frontend.releaseConfigHTTPPort" . | quote }}
      disableHttps: {{ .Values.applaunchpadConfig.disableHttps }}
      desktopDomain: {{ .Values.applaunchpadConfig.cloudDomain }}
      userDomains:
        - name: {{ .Values.applaunchpadConfig.cloudDomain }}
          secretName: {{ .Values.applaunchpadConfig.certSecretName }}
    common:
      guideEnabled: {{ .Values.applaunchpadConfig.guideEnabled }}
      apiEnabled:  {{ .Values.applaunchpadConfig.apiEnabled }}
      gpuEnabled: {{ .Values.applaunchpadConfig.gpuEnabled }}
      networkStorageEnabled: {{ .Values.applaunchpadConfig.networkStorageEnabled }}
    launchpad:
      pvcStorageMax: {{ .Values.applaunchpadConfig.pvcStorageMax }}
      currencySymbol:  {{ .Values.applaunchpadConfig.currencySymbol | quote }}
      infrastructure:
        provider: alibaba
        requiresDomainReg:  {{ eq .Values.applaunchpadConfig.currencySymbol "shellCoin"  }}
        domainRegQueryLink: https://beian.miit.gov.cn/#/Integrated/index
        domainBindingDocumentationLink: null
      eventAnalyze:
        enabled: false
        fastGPTKey: ""
      imagePorts:
        enabled: {{ .Values.applaunchpadConfig.imagePortsEnabled }}
        trustedRegistries:{{ toYaml .Values.applaunchpadConfig.imagePortsTrustedRegistries | nindent 10 }}
      publicDomain:
        customPrefixEnabled: {{ .Values.applaunchpadConfig.customPublicDomainPrefixEnabled }}
        reservedPrefixes:{{ toYaml .Values.applaunchpadConfig.publicDomainReservedPrefixes | nindent 10 }}
      customDomain:
        mode: {{ .Values.applaunchpadConfig.customDomainMode | quote }}
        certificate:
          tlsSecretName: {{ .Values.applaunchpadConfig.customDomainCertificateSecretName | quote }}
      components:
        monitor:
          url: {{ .Values.applaunchpadConfig.monitorUrl }}
        billing:
          url: {{ .Values.applaunchpadConfig.billingUrl }}
          secret: {{ .Values.applaunchpadConfig.jwtInternal }}
        log:
          url: {{ .Values.applaunchpadConfig.logUrl }}
      appResourceFormSliderConfig:
        default:
          cpu: {{ toJson .Values.applaunchpadConfig.appResourceFormSliderConfig.default.cpu }}
          memory: {{ toJson .Values.applaunchpadConfig.appResourceFormSliderConfig.default.memory }}
          ephemeralStorage: {{ toJson .Values.applaunchpadConfig.appResourceFormSliderConfig.default.ephemeralStorage }}
        default-gpu:
          cpu: {{ toJson .Values.applaunchpadConfig.appResourceFormSliderConfig.defaultGPU.cpu }}
          memory: {{ toJson .Values.applaunchpadConfig.appResourceFormSliderConfig.defaultGPU.memory }}
          ephemeralStorage:  {{ toJson .Values.applaunchpadConfig.appResourceFormSliderConfig.defaultGPU.ephemeralStorage }}
      fileManger:
        uploadLimit: {{.Values.applaunchpadConfig.fileManger.uploadLimit}}
        downloadLimit: {{.Values.applaunchpadConfig.fileManger.downloadLimit}}
