apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: invite
  namespace: app-system
spec:
  data:
    desc: invite
    url: {{ include "invite-frontend.appUrl" . | quote }}
  icon: {{ printf "%s/logo.svg" (include "invite-frontend.appUrl" .) | quote }}
  i18n:
    zh:
      name: 邀请注册
    zh-Hans:
      name: 邀请注册
  menuData:
  name: invite
  type: iframe
  displayType: normal
