apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "invite-frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "invite-frontend.labels" . | nindent 4 }}
data:
  config.yaml: |-
    addr: :{{ .Values.service.port }}
