FROM ubuntu:22.04
ARG TARGETARCH

WORKDIR /usr/bin/

RUN apt update -y \
  && apt update -y \
  && apt install -y uidmap fuse-overlayfs \
  && rm -rf /var/lib/apt/lists/*

COPY --chmod=0755 /bin/sealos-$TARGETARCH/sealos .
ENTRYPOINT ["/usr/bin/sealos"]
