FROM ubuntu:22.04

COPY sealos /usr/bin/

RUN  apt update -y \
  && apt install -y uidmap fuse-overlayfs \
  && rm -rf /var/lib/apt/lists/*

# nosemgrep: dockerfile.security.missing-user.missing-user
ENTRYPOINT ["/usr/bin/sealos"]
# nosemgrep: dockerfile.security.missing-user.missing-user
CMD ["--help"]
