image: ghcr.io/labring/sealos-kubepanel-frontend:latest
imagePullPolicy: Always
imagePullSecrets: []

fullnameOverride: "kubepanel-frontend"
replicaCount: 1

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

service:
  type: ClusterIP
  port: 3000

ingress:
  className: nginx
  host: ""
  annotations: {}

kubepanelConfig:
  cloudDomain: "127.0.0.1.nip.io"
  cloudPort: ""
  httpPort: ""
  disableHttps: false
  certSecretName: "wildcard-cert"

startupProbe:
  httpGet:
    path: /api/platform/init-data
    port: http
  periodSeconds: 2
  timeoutSeconds: 3
  failureThreshold: 30
readinessProbe:
  httpGet:
    path: /api/platform/init-data
    port: http
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 6
livenessProbe:
  httpGet:
    path: /api/platform/init-data
    port: http
  periodSeconds: 20
  timeoutSeconds: 3
  failureThreshold: 3

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 10m
    memory: 128Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - kubepanel-frontend
          topologyKey: kubernetes.io/hostname

tests:
  image: busybox:1.36.1
  imagePullPolicy: IfNotPresent
  path: /api/platform/init-data
