import { MERGE_USER_READY, PROVIDER_STATUS, RESPONSE_MESSAGE } from './utils';

enum _BIND_STATUS {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  NOT_SUPPORT = 'NOT_SUPPORT',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  DB_ERROR = 'DB_ERROR'
}
export const BIND_STATUS = Object.assign(
  Object.assign({}, MERGE_USER_READY, _BIND_STATUS, RESPONSE_MESSAGE),
  PROVIDER_STATUS
);
export type BIND_STATUS = typeof BIND_STATUS;
