import { RESPONSE_MESSAGE } from './utils';

enum _EMAIL_STATUS {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_PARAMS = 'INVALID_PARAMS',
  NOT_SUPPORT = 'NOT_SUPPORT',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  DB_ERROR = 'DB_ERROR'
}
export const EMAIL_STATUS = Object.assign({}, _EMAIL_STATUS, RESPONSE_MESSAGE);
export type EMAIL_STATUS = typeof EMAIL_STATUS;
