import { _ACCOUNT_STATUS, RESPONSE_MESSAGE } from './utils';

enum _USER_MERGE_STATUS {
  NOT_SUPPORT = 'NOT_SUPPORT',
  OAUTH_PROVIDER_NOT_FOUND = 'OAUTH_PROVIDER_NOT_FOUND',
  EXIST_SAME_OAUTH_PROVIDER = 'EXIST_SAME_OAUTH_PROVIDER',
  USER_NOT_FOUND = 'USER_NOT_FOUND'
}
export const USER_MERGE_STATUS = Object.assign(
  {},
  _USER_MERGE_STATUS,
  RESPONSE_MESSAGE,
  _ACCOUNT_STATUS
);
export type USER_MERGE_STATUS = typeof USER_MERGE_STATUS;
