export enum RESPONSE_MESSAGE {
  RESULT_SUCCESS = 'RESULT_SUCCESS',
  INTERNAL_SERVER_ERROR = 'INTERNAL SERVER ERROR'
}

export enum _ACCOUNT_STATUS {
  INSUFFICENT_BALANCE = 'INSUFFICENT_BALANCE',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND'
}
export enum MERGE_USER_READY {
  MERGE_USER_CONTINUE = 'USER_MERGE',
  MERGE_USER_PROVIDER_CONFLICT = 'PROVIDER_CONFLICT'
}
export enum PROVIDER_STATUS {
  PROVIDER_NOT_FOUND = 'PROVIDER_NOT_FOUND',
  PROVIDER_EXIST = 'PROVIDER_EXIST'
}
