package doubaoaudio

import (
	"github.com/labring/sealos/service/aiproxy/model"
	"github.com/labring/sealos/service/aiproxy/relay/relaymode"
)

// https://www.volcengine.com/docs/6561/1257543

var ModelList = []*model.ModelConfig{
	{
		Model:      "Doubao-tts",
		Type:       relaymode.AudioSpeech,
		Owner:      model.ModelOwnerDoubao,
		InputPrice: 0.5,
		RPM:        60,
		Config: model.NewModelConfig(
			model.WithModelConfigSupportFormats([]string{
				"pcm",
				"mp3",
				"wav",
				"ogg_opus",
			}),
			model.WithModelConfigSupportVoices([]string{
				"zh_female_cancan_mars_bigtts",
				"zh_female_qingxinnvsheng_mars_bigtts",
				"zh_female_shuangkuaisisi_moon_bigtts",
				"zh_male_wennuanahu_moon_bigtts",
				"zh_male_shaonianzixin_moon_bigtts",
				"zh_female_zhixingnvsheng_mars_bigtts",
				"zh_male_qingshuangnanda_mars_bigtts",
				"zh_female_linjianvhai_moon_bigtts",
				"zh_male_yuanboxiaoshu_moon_bigtts",
				"zh_male_yangguangqingnian_moon_bigtts",
				"zh_female_tianmeixiaoyuan_moon_bigtts",
				"zh_female_qingchezizi_moon_bigtts",
				"zh_male_jieshuoxiaoming_moon_bigtts",
				"zh_female_kailangjiejie_moon_bigtts",
				"zh_male_linjiananhai_moon_bigtts",
				"zh_female_tianmeiyueyue_moon_bigtts",
				"zh_female_xinlingjitang_moon_bigtts",
				"en_male_smith_mars_bigtts",
				"en_female_anna_mars_bigtts",
				"en_male_adam_mars_bigtts",
				"en_female_sarah_mars_bigtts",
				"en_male_dryw_mars_bigtts",
				"multi_male_jingqiangkanye_moon_bigtts",
				"multi_female_shuangkuaisisi_moon_bigtts",
				"multi_male_wanqudashu_moon_bigtts",
				"multi_female_gaolengyujie_moon_bigtts",
				"zh_male_jingqiangkanye_moon_bigtts",
				"zh_female_wanwanxiaohe_moon_bigtts",
				"zh_female_wanqudashu_moon_bigtts",
				"zh_female_daimengchuanmei_moon_bigtts",
				"zh_male_guozhoudege_moon_bigtts",
				"zh_male_beijingxiaoye_moon_bigtts",
				"zh_male_haoyuxiaoge_moon_bigtts",
				"zh_male_guangxiyuanzhou_moon_bigtts",
				"zh_female_meituojieer_moon_bigtts",
				"zh_male_yuzhouzixuan_moon_bigtts",
				"zh_male_naiqimengwa_mars_bigtts",
				"zh_female_popo_mars_bigtts",
				"zh_female_gaolengyujie_moon_bigtts",
				"zh_male_aojiaobazong_moon_bigtts",
				"zh_female_meilinvyou_moon_bigtts",
				"zh_male_shenyeboke_moon_bigtts",
				"zh_female_sajiaonvyou_moon_bigtts",
				"zh_female_yuanqinvyou_moon_bigtts",
				"ICL_zh_female_bingruoshaonv_tob",
				"ICL_zh_female_huoponvhai_tob",
				"zh_male_dongfanghaoran_moon_bigtts",
				"ICL_zh_female_heainainai_tob",
				"ICL_zh_female_linjuayi_tob",
				"zh_female_wenrouxiaoya_moon_bigtts",
				"zh_male_tiancaitongsheng_mars_bigtts",
				"zh_male_sunwukong_mars_bigtts",
				"zh_male_xionger_mars_bigtts",
				"zh_female_peiqi_mars_bigtts",
				"zh_female_wuzetian_mars_bigtts",
				"zh_female_gujie_mars_bigtts",
				"zh_female_yingtaowanzi_mars_bigtts",
				"zh_male_chunhui_mars_bigtts",
				"zh_female_shaoergushi_mars_bigtts",
				"zh_male_silang_mars_bigtts",
				"zh_male_jieshuonansheng_mars_bigtts",
				"zh_female_jitangmeimei_mars_bigtts",
				"zh_female_tiexinnvsheng_mars_bigtts",
				"zh_female_qiaopinvsheng_mars_bigtts",
				"zh_female_mengyatou_mars_bigtts",
				"zh_male_changtianyi_mars_bigtts",
				"zh_male_ruyaqingnian_mars_bigtts",
				"zh_male_baqiqingshu_mars_bigtts",
				"zh_male_qingcang_mars_bigtts",
				"zh_female_gufengshaoyu_mars_bigtts",
				"zh_female_wenroushunv_mars_bigtts",
			}),
		),
	},

	// {
	// 	Model:      "Doubao-stt",
	// 	Type:       relaymode.AudioTranscription,
	// 	Owner:      model.ModelOwnerDoubao,
	// 	InputPrice: 2.3,
	// },
}
