export const VERIFICATION_CODE_SCENARIOS = {
  PHONE: 'PHONE',
  PHONE_LOGIN: 'PHONE_LOGIN',
  PHONE_BIND: 'PHONE_BIND',
  PHONE_CHANGE_OLD: 'PHONE_CHANGE_OLD',
  PHONE_CHANGE_NEW: 'PHONE_CHANGE_NEW',
  PHONE_UNBIND: 'PHONE_UNBIND',
  EMAIL: 'EMAIL',
  EMAIL_LOGIN: 'EMAIL_LOGIN',
  EMAIL_BIND: 'EMAIL_BIND',
  EMAIL_UNBIND: 'EMAIL_UNBIND',
  EMAIL_CHANGE_OLD: 'EMAIL_CHANGE_OLD',
  EMAIL_CHANGE_NEW: 'EMAIL_CHANGE_NEW',
  MERGE_USER: 'MERGE_USER'
} as const;

export type VerificationCodeScenario =
  (typeof VERIFICATION_CODE_SCENARIOS)[keyof typeof VERIFICATION_CODE_SCENARIOS];

export const VERIFICATION_PROVIDER_TYPES = {
  PHONE: 'PHONE',
  EMAIL: 'EMAIL',
  GITHUB: 'GITHUB',
  WECHAT: 'WECHAT',
  GOOGLE: 'GOOGLE',
  PASSWORD: 'PASSWORD',
  OAUTH2: 'OAUTH2'
} as const;

export type VerificationProviderType =
  (typeof VERIFICATION_PROVIDER_TYPES)[keyof typeof VERIFICATION_PROVIDER_TYPES];

export const OAUTH_PROVIDERS = {
  GITHUB: 'GITHUB',
  WECHAT: 'WECHAT',
  GOOGLE: 'GOOGLE',
  OAUTH2: 'OAUTH2'
} as const;

export type OAuthProvider = (typeof OAUTH_PROVIDERS)[keyof typeof OAUTH_PROVIDERS];

export const OAUTH_VERIFICATION_SCENARIOS = {
  LOGIN_QR: 'LOGIN_QR',
  LOGIN_CALLBACK: 'LOGIN_CALLBACK',
  BIND: 'BIND',
  UNBIND: 'UNBIND',
  LINK: 'LINK'
} as const;

export type OAuthVerificationScenario =
  (typeof OAUTH_VERIFICATION_SCENARIOS)[keyof typeof OAUTH_VERIFICATION_SCENARIOS];
