# Custom values for database-monitor.

replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 5m
    memory: 64Mi

databaseMonitorConfig:
  prometheusServiceHost: "http://vmselect-vm-stack-victoria-metrics-k8s-stack.vm.svc:8481/select/0/prometheus/"
