apiVersion: app.sealos.io/v1
kind: App
metadata:
  name: aiproxy
  namespace: app-system
spec:
  data:
    desc: Sealos AI Proxy
    url: https://{{ include "aiproxy.fullname" . }}.{{ .Values.cloudDomain }}{{- if and .Values.cloudPort (ne (toString .Values.cloudPort) "443") }}:{{ .Values.cloudPort }}{{- end }}
  displayType: more
  i18n:
    zh:
      name: AI Proxy
    zh-Hans:
      name: AI Proxy
  icon: https://{{ include "aiproxy.fullname" . }}.{{ .Values.cloudDomain }}{{- if and .Values.cloudPort (ne (toString .Values.cloudPort) "443") }}:{{ .Values.cloudPort }}{{- end }}/logo.svg
  name: AI Proxy
  type: iframe
