apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cronjob-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cronjob-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cronjob-frontend.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        {{- include "cronjob-frontend.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SEALOS_DOMAIN
              value: {{ .Values.cronjobConfig.cloudDomain | quote }}
            - name: APPLAUNCHPAD_URL
              value: {{ printf "applaunchpad.%s" .Values.cronjobConfig.cloudDomain | quote }}
            - name: SUCCESSFUL_JOBS_HISTORY_LIMIT
              value: {{ .Values.cronjobConfig.successfulJobsHistoryLimit | quote }}
            - name: FAILED_JOBS_HISTORY_LIMIT
              value: {{ .Values.cronjobConfig.failedJobsHistoryLimit | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: cronjob-frontend-volume
              mountPath: /app/data/config.yaml
              subPath: config.yaml
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: cronjob-frontend-volume
          configMap:
            name: {{ include "cronjob-frontend.fullname" . }}-config
