#!/bin/sh
STAGE_FILES=$(git diff --cached --name-only --diff-filter=ACM -- 'desktop/frontend/src/*.ts' 'desktop/frontend/src/*.tsx' 'desktop/frontend/src/*.scss')

if test ${#STAGE_FILES} -gt 0
then
	cd desktop/frontend
	echo 'Frontend formatting'
	npm run formatFrontend
else
	echo 'No need to format'
fi
exit 0