apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "objectstorage-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "objectstorage-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "objectstorage-frontend.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        {{- include "objectstorage-frontend.labels" . | nindent 8 }}
        {{- with (omit .Values.podLabels "app" "helm.sh/chart" "app.kubernetes.io/name" "app.kubernetes.io/instance" "app.kubernetes.io/managed-by" "app.kubernetes.io/version") }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.service.port | quote }}
            - name: MONITOR_URL
              value: {{ .Values.objectstorageConfig.monitorUrl | quote }}
            - name: APP_LAUNCHPAD_URL
              value: {{ .Values.objectstorageConfig.appLaunchpadUrl | quote }}
            - name: SEALOS_DOMAIN
              value: {{ .Values.objectstorageConfig.cloudDomain | quote }}
            - name: SEALOS_ACCOUNT_SERVER
              value: {{ .Values.objectstorageConfig.accountServer | quote }}
            - name: SEALOS_ACCOUNT_SERVER_TOKEN_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "objectstorage-frontend.fullname" . }}-secret
                  key: account-server-token-jwt-key
            - name: SEALOS_APP_TOKEN_JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "objectstorage-frontend.fullname" . }}-secret
                  key: app-token-jwt-key
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
