apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "objectstorage-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "objectstorage-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      {{- include "objectstorage-frontend.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  template:
    metadata:
      labels:
        {{- include "objectstorage-frontend.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.securityContext }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: MONITOR_URL
              value: {{ .Values.objectstorageConfig.monitorUrl | quote }}
            - name: APP_LAUNCHPAD_URL
              value: {{ .Values.objectstorageConfig.appLaunchpadUrl | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          volumeMounts:
            - name: object-storage-frontend-volume
              mountPath: /app/data/config.yaml
              subPath: config.yaml
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: object-storage-frontend-volume
          configMap:
            name: {{ include "objectstorage-frontend.fullname" . }}-config
