apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "objectstorage-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.className | quote }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~* \.(js|css|gif|jpe?g|png)) {
        expires 30d;
        add_header Cache-Control "public";
      }
    nginx.ingress.kubernetes.io/proxy-body-size: 3g
    nginx.ingress.kubernetes.io/proxy-next-upstream-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | quote }}
  rules:
    - host: {{ include "objectstorage-frontend.host" . | quote }}
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: {{ include "objectstorage-frontend.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- if not (eq (toString .Values.objectstorageConfig.disableHttps) "true") }}
  tls:
    - hosts:
        - {{ include "objectstorage-frontend.host" . | quote }}
      secretName: {{ .Values.objectstorageConfig.certSecretName | quote }}
  {{- end }}
