apiVersion: v1
kind: Secret
metadata:
  name: {{ include "objectstorage-frontend.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "objectstorage-frontend.labels" . | nindent 4 }}
type: Opaque
stringData:
  account-server-token-jwt-key: {{ .Values.objectstorageConfig.accountServerTokenJwtKey | quote }}
  app-token-jwt-key: {{ .Values.objectstorageConfig.appTokenJwtKey | quote }}
