apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "database-monitor.labels" . | nindent 4 }}
    app: {{ .Release.Name }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Release.Name }}
