apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terminal-frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terminal-frontend.labels" . | nindent 4 }}
data:
  .env: |-
    TTYD_IMAGE={{ .Values.terminalConfig.ttydImage }}
    SITE={{ include "terminal-frontend.cloudOrigin" . }}
    KEEPALIVED={{ .Values.terminalConfig.keepalived }}
  config.yaml: |-
    addr: :3000
