apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "terminal-frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "terminal-frontend.labels" . | nindent 4 }}
data:
  TTYD_IMAGE: {{ .Values.terminalConfig.ttydImage | quote }}
  SITE: {{ include "terminal-frontend.cloudOrigin" . | quote }}
  KEEPALIVED: {{ .Values.terminalConfig.keepalived | quote }}
  config.yaml: |-
    addr: :3000
