import { MERGE_USER_READY, PROVIDER_STATUS, RESPONSE_MESSAGE } from './utils';

enum _CHANGE_BIND_STATUS {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  NOT_SUPPORT = 'NOT_SUPPORT',
  // OLD_PROVIDER_NOT_EXIST = 'PROVIDER_NOT_EXIST',
  // NEW_PROVIDER_USED_CONFLICT = 'NEW_PROVIDER_USED_CONFLICT',
  // NEW_PROVIDER_USED_MERGE = 'NEW_PROVIDER_USED_MERGE',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  DB_ERROR = 'DB_ERROR'
}
export const CHANGE_BIND_STATUS = Object.assign(
  Object.assign({}, _CHANGE_BIND_STATUS, MERGE_USER_READY, RESPONSE_MESSAGE),
  PROVIDER_STATUS
);
export type CHANGE_BIND_STATUS = typeof CHANGE_BIND_STATUS;
