import { _ACCOUNT_STATUS, RESPONSE_MESSAGE } from './utils';

enum _RESOURCE_STATUS {
  USER_CR_NOT_FOUND = 'USER_CR_NOT_FOUND',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  OAUTHPROVIDER_NOT_FOUND = 'OAUTHPROVIDER_NOT_FOUND',
  PRIVATE_WORKSPACE_NOT_FOUND = 'PRIVATE_WORKSPACE_NOT_FOUND',
  GET_RESOURCE_ERROR = 'GET_RESOURCE_ERROR',
  REMAIN_OTHER_REGION_RESOURCE = 'REMAIN_OTHER_REGION_RESOURCE',
  REMAIN_WORKSACE_OWNER = 'REMAIN_WORKSACE_OWNER',
  REMAIN_CVM = 'REMAIN_CVM',
  REMAIN_APP = 'REMAIN_APP',
  REMAIN_TEMPLATE = 'REMAIN_TEMPLATE',
  REMAIN_OBJECT_STORAGE = 'REMAIN_OBJECT_STORAGE',
  REMAIN_DATABASE = 'REMAIN_DATABASE',
  KUBECONFIG_NOT_FOUND = 'KUBECONFIG_NOT_FOUND'
}

export const RESOURCE_STATUS = Object.assign(
  {},
  _RESOURCE_STATUS,
  RESPONSE_MESSAGE,
  _ACCOUNT_STATUS
);
export type RESOURCE_STATUS = typeof RESOURCE_STATUS;
