import { PROVIDER_STATUS, RESPONSE_MESSAGE } from './utils';

enum _UNBIND_STATUS {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  NOT_SUPPORT = 'NOT_SUPPORT',
  RESOURCE_CONFLICT = 'RESOURCE_CONFLICT',
  DB_ERROR = 'DB_ERROR'
}
export const UNBIND_STATUS = Object.assign({}, _UNBIND_STATUS, RESPONSE_MESSAGE, PROVIDER_STATUS);
export type UNBIND_STATUS = typeof UNBIND_STATUS;
