# Default values for cronjob-frontend helm chart.

image: ghcr.io/labring/sealos-cronjob-frontend:latest
imagePullPolicy: Always

imagePullSecrets: []
fullnameOverride: "cronjob-frontend"

replicaCount: 1

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

service:
  type: ClusterIP
  port: 3000

ingress:
  className: nginx
  host: ""
  annotations: {}

cronjobConfig:
  cloudDomain: "127.0.0.1.nip.io"
  cloudPort: ""
  httpPort: ""
  disableHttps: false
  certSecretName: "wildcard-cert"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  podCpuMilliCores: 50
  podMemoryMiB: 64

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 10m
    memory: 128Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: "app"
                operator: In
                values:
                  - cronjob-frontend
          topologyKey: "kubernetes.io/hostname"
