{{- if .Values.accountEnv.accountAdminJwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.adminJwtSecretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    control-plane: controller-manager
    {{- include "account-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  ACCOUNT_ADMIN_JWT_SECRET: {{ .Values.accountEnv.accountAdminJwtSecret | quote }}
{{- end }}
