replicaCount: 1

image: ghcr.io/labring/sealos-launchpad-service:latest
imagePullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 5m
    memory: 64Mi

service:
  port: 8428

startupProbe:
  httpGet:
    path: /health
    port: 8428
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 30

livenessProbe:
  httpGet:
    path: /health
    port: 8428
  initialDelaySeconds: 3
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8428
  initialDelaySeconds: 3
  periodSeconds: 5
  failureThreshold: 6

launchpadMonitorConfig:
  vmServiceHost: "http://vmselect-vm-stack-victoria-metrics-k8s-stack.vm.svc:8481/select/0/prometheus/"
