import Head from 'next/head';
import { Flex } from '@chakra-ui/react';

export default function Home({ children }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex w="100vw" h="100vh" bgColor={'#F2F2F4'}>
          {children}
        </Flex>
      </main>
    </>
  );
}
