export enum MergeUserEvent {
  '<MERGE_USER>_MERGE_OAUTH_PROVIDER' = '<MERGE_USER>_MERGE_OAUTH_PROVIDER',
  '<MERGE_USER>_PUB_TRANSACTION' = '<MERGE_USER>_PUB_TRANSACTION',
  '<MERGE_USER>_MERGE_WORKSPACE' = '<MERGE_USER>_MERGE_WORKSPACE',
  '<MERGE_USER>_COMMIT' = '<MERGE_USER>_COMMIT',
  '<MERGE_USER>_SET_DELETE_USER' = '<MERGE_USER>_SET_DELETE_USER'
}
// export type EventName = 'DELETE_USER';
export enum DeleteUserEvent {
  '<DELETE_USER>_SET_LOCK_USER' = '<DELETE_USER>_SET_LOCK_USER',
  '<DELETE_USER>_SET_LOCK_WORKSPACE' = '<DELETE_USER>_SET_LOCK_WORKSPACE',
  '<DELETE_USER>_PUB_TRANSACTION' = '<DELETE_USER>_PUB_TRANSACTION',
  '<DELETE_USER>_DELETE_USERCR' = '<DELETE_USER>_DELETE_USERCR',
  '<DELETE_USER>_COMMIT' = '<DELETE_USER>_COMMIT'
}
