apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devbox-frontend.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devbox-frontend.labels" . | nindent 4 }}
data:
  config.yaml: |-
    addr: :3000
