apiVersion: v1
kind: Service
metadata:
  name: {{ include "devbox-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devbox-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "devbox-frontend.selectorLabels" . | nindent 4 }}
