# Default values for invite-frontend helm chart.

image: ghcr.io/labring/sealos-invite-frontend:latest
imagePullPolicy: Always

imagePullSecrets: []
fullnameOverride: "invite-frontend"

replicaCount: 1

podAnnotations: {}
podLabels: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001

securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

service:
  type: ClusterIP
  port: 3000

ingress:
  className: nginx
  host: ""
  annotations: {}

inviteConfig:
  cloudDomain: "127.0.0.1.nip.io"
  cloudPort: ""
  httpPort: ""
  disableHttps: false
  certSecretName: "wildcard-cert"
  lafBaseUrl: ""
  giftRatio: "0.1"

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 10m
    memory: 128Mi

affinity: {}
