apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "service-vlogs.labels" . | nindent 4 }}
    app: {{ .Release.Name }}
data:
  config.yml: |
    server:
      addr: ":{{ .Values.service.port }}"
      path: {{ .Values.serviceVlogsConfig.path | quote }}
      username: {{ .Values.serviceVlogsConfig.username | quote }}
      password: {{ .Values.serviceVlogsConfig.password | quote }}
