FROM ubuntu:22.04

RUN apt update -y \
  && apt install -y uidmap fuse-overlayfs \
  && rm -rf /var/lib/apt/lists/*

COPY sreg /usr/bin/

# nosemgrep: dockerfile.security.missing-user.missing-user
ENTRYPOINT ["/usr/bin/sreg"]
# nosemgrep: dockerfile.security.missing-user.missing-user
CMD ["--help"]
