import { useEffect, useState, useCallback } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { sealosApp, createSealosApp } from "sealos-desktop-sdk";

export default function Home() {
  const [showData, setShowData] = useState<any>();
  useEffect(() => {
    /* Must be used within useEffect. Make sure it is in the browser */
    createSealosApp({
      appKey: "sealos-app-sdk-demo",
    });
    return sealosApp.init();
  }, []);

  const getUserInfo = useCallback(async () => {
    const res = await sealosApp.getUserInfo();
    setShowData(JSON.stringify(res));
  }, []);
  const getApps = useCallback(async () => {
    const res = await sealosApp.getApps();
    setShowData(JSON.stringify(res));
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div
          style={{
            width: "50vw",
            margin: "auto",
            display: "flex",
            justifyContent: "space-around",
          }}
        >
          <button onClick={getUserInfo}>getUserInfo</button>
          <button onClick={getApps}>get APP mock data</button>
        </div>

        <div
          style={{
            maxWidth: "100vw",
          }}
        >
          {showData}
        </div>
      </main>
    </>
  );
}
