image: ghcr.io/labring/sealos-objectstorage-frontend:latest
imagePullPolicy: Always
imagePullSecrets: []

fullnameOverride: "object-storage-frontend"
replicaCount: 1
revisionHistoryLimit: 1

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - "ALL"

service:
  type: ClusterIP
  port: 3000

ingress:
  className: nginx
  host: ""
  annotations: {}

objectstorageConfig:
  cloudDomain: "127.0.0.1.nip.io"
  cloudPort: ""
  httpPort: ""
  disableHttps: false
  certSecretName: "wildcard-cert"
  monitorUrl: "http://object-storage-monitor.objectstorage-system.svc.cluster.local:9090/q"
  appLaunchpadUrl: "http://applaunchpad-frontend.applaunchpad-frontend.svc.cluster.local:3000/api/v1alpha"
  accountServer: "http://account-service.account-system.svc:2333"
  accountServerTokenJwtKey: ""
  appTokenJwtKey: ""

startupProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 2
  timeoutSeconds: 3
  failureThreshold: 30
readinessProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 6
livenessProbe:
  httpGet:
    path: /
    port: http
  periodSeconds: 20
  timeoutSeconds: 3
  failureThreshold: 3

resources:
  limits:
    cpu: 2000m
    memory: 2048Mi
  requests:
    cpu: 10m
    memory: 128Mi

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - object-storage-frontend
          topologyKey: kubernetes.io/hostname

tests:
  image: busybox:1.36.1
  imagePullPolicy: IfNotPresent
  path: /
