apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "template-frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "template-frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "template-frontend.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        {{- include "template-frontend.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          image: {{ .Values.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          env:
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: {{ .Values.templateConfig.tlsRejectUnauthorized | quote }}
            - name: TEMPLATE_REPO_URL
              value: {{ .Values.templateConfig.templateRepoUrl | quote }}
            - name: TEMPLATE_REPO_BRANCH
              value: {{ .Values.templateConfig.templateRepoBranch | quote }}
            - name: TEMPLATE_REPO_PROVIDER
              value: {{ .Values.templateConfig.templateRepoProvider | quote }}
            - name: TEMPLATE_REPO_FOLDER
              value: {{ .Values.templateConfig.templateRepoPath | quote }}
            - name: TEMPLATE_CATEGORIES
              value: {{ .Values.templateConfig.templateCategories | quote }}
            - name: TEMPLATE_CATEGORIES_PATH
              value: "config/categories.json"
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          volumeMounts:
            - name: template-frontend-volume
              mountPath: /app/providers/template/.env
              subPath: .env
            - name: template-frontend-volume
              mountPath: /config.yaml
              subPath: config.yaml
            - name: template-frontend-volume
              mountPath: /app/data/config.json
              subPath: config.json
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: template-frontend-volume
          configMap:
            defaultMode: 420
            name: {{ include "template-frontend.fullname" . }}-config
