import type { NextPage } from 'next'
import Head from 'next/head'
import { UserOutlined, LockOutlined } from '@ant-design/icons'
import { Input, Button } from 'antd'
import styles from '../styles/Login.module.css'
import { useRouter } from 'next/router'




const Login: NextPage = () => {
    const router = useRouter()

  const handleLogin = () => {
    router.push('/dashboard')
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Login Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2 className={styles.title}>
          Sealos Login
        </h2>

        <div className={styles.form}>
          <Input size="large" placeholder="please input your account" prefix={<UserOutlined />} />
          <br />
          <Input size="large" placeholder="please input your password" prefix={<LockOutlined />} />
          <br />
          <Button type='primary' onClick={handleLogin}>Submit</Button>
        </div>
      </main>
    </div>
  )
}

export default Login
