name: Release Components

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag for manual release"
        required: false
        default: ""
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag for manual release"
        required: false
        default: ""
        type: string

permissions:
  contents: read
  packages: write

jobs:
  release-controllers:
    uses: ./.github/workflows/controllers.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.tag }}
      disable_cilint: true
      force_all: true
    secrets: inherit

  release-frontends:
    uses: ./.github/workflows/frontends.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.tag }}
      force_all: true
    secrets: inherit

  release-service:
    uses: ./.github/workflows/services.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.tag }}
      disable_cilint: true
      force_all: true
    secrets: inherit

  release-webhook:
    uses: ./.github/workflows/webhooks.yml
    with:
      push_image: true
      push_image_tag: ${{ inputs.tag }}
      disable_cilint: true
    secrets: inherit
