name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag"
        required: false
        default: ""
        type: string
  push:
    tags:
      - "*"

jobs:
  release-components:
    permissions:
      contents: write
      packages: write
    uses: ./.github/workflows/cloud-release.yml
    secrets: inherit
    with:
      tag: ${{ inputs.tag || github.ref_name }}
